# Generated by Django 5.0.6 on 2024-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('soil_moisture', models.FloatField()),
            ],
            options={
                'db_table': 'soil',
            },
        ),
    ]
