# Generated by Django 5.0.6 on 2024-07-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_moisture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soilmoisturedata',
            table='soil_moisture',
        ),
    ]
