# Generated by Django 5.0.6 on 2024-07-16 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soil_moisture', '0002_alter_soilmoisturedata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='soilmoisturedata',
            table=None,
        ),
    ]
